#!/bin/bash

function usage() {
    echo "runenv start|kill"
}

function start() {
    echo "starting env..."
    tmux new-session -d -s runenv
    tmux new-window -t runenv:1 -n "mongo" "startmongo"
    tmux new-window -t runenv:2 -n "redis" "startredis"
    tmux new-window -t runenv:3 -n "juggernaut" "juggernaut"
    echo "started env"
}

function kill() {
    echo "killing env..."
    killall node
    killall redis-server
    killall mongod
    tmux kill-session -t runenv
    echo "killed env"
}

if [ -z $1 ]; then
    usage
    exit 1
fi

case $1 in
    start)
        start
        ;;
    kill)
        kill
        ;;
    *)
        usage
        exit 1
    ;;
esac
